version: '3'

services:
  ftp:
    build: .
    ports:
      - "2121:21"
    restart: always
    networks:
      - esiee-network

  web:
    image: php:8.0-apache
    platform: linux/arm64
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - esiee-network

  db:
    image: mysql:8.0
    platform: linux/arm64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: devLife
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - esiee-network

  phpmyadmin:
    image: arm64v8/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: user_dev
      PMA_PASSWORD: user_password
    depends_on:
      - db
    networks:
      - esiee-network

networks:
  esiee-network:

volumes:
  db_data: