version: '3'

services:
  ftp:
    build: .
    ports:
      - "2121:21"
    restart: always
    networks:
      - esiee-network

  web:
    image: php:8.0-apache
    platform: linux/arm64
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - esiee-network
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"

  db:
    image: mysql:8.0
    platform: linux/arm64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: devLife
      MYSQL_USER: userphp
      MYSQL_PASSWORD: passuserphp
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - esiee-network

  phpmyadmin:
    image: arm64v8/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_USER=userphp
      - MYSQL_PASSWORD=passuserphp
      - MYSQL_ROOT_PASSWORD=root_password
      - PMA_PORT=3306
      - UPLOAD_LIMIT=300M
    depends_on:
      - db
    networks:
      - esiee-network

networks:
  esiee-network:

volumes:
  db_data: